version: '3'
services:
  api:
    container_name: "api"
    volumes:
      - ./src:/src
    build: .
    ports:
      - 8080:8080
    
  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=exam_scores
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: